/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Empresa (Tenant) y primer Administrador
         * @description spec-001. Crea el tenant, su primer usuario Administrador y registra la
         *     **aceptación del tratamiento de datos (Habeas Data)**. Crea por defecto una
         *     Suscripción en plan Free (1 vehículo). Operación pública (no requiere JWT).
         */
        post: operations["registrarTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos del tenant actual */
        get: operations["obtenerTenantActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuarios del tenant */
        get: operations["listarUsuarios"];
        put?: never;
        /**
         * Invitar un usuario y asignarle roles
         * @description spec-002. Solo Administrador. Emite el evento `UsuarioInvitado`.
         */
        post: operations["invitarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar roles o estado de un usuario
         * @description spec-002. Cambia roles o suspende/reactiva (Administrador).
         */
        patch: operations["actualizarUsuario"];
        trace?: never;
    };
    "/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar vehículos del tenant */
        get: operations["listarVehiculos"];
        put?: never;
        /**
         * Registrar un vehículo
         * @description spec-003. La **placa es única por tenant**. Emite `VehiculoRegistrado`.
         */
        post: operations["registrarVehiculo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/{vehiculoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        /** Obtener un vehículo */
        get: operations["obtenerVehiculo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar datos básicos del vehículo */
        patch: operations["actualizarVehiculo"];
        trace?: never;
    };
    "/vehiculos/{vehiculoId}/odometro": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar una lectura de odómetro
         * @description spec-003. El odómetro es **monótonamente creciente**: una lectura menor a la
         *     última registrada se rechaza (422). Emite `OdometroActualizado`.
         */
        post: operations["registrarOdometro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conductores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar conductores del tenant */
        get: operations["listarConductores"];
        put?: never;
        /**
         * Registrar un conductor y su licencia
         * @description spec-004. Emite `ConductorRegistrado`. Minimización de datos (Habeas Data).
         */
        post: operations["registrarConductor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conductores/{conductorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conductorId: components["parameters"]["ConductorId"];
            };
            cookie?: never;
        };
        /** Obtener un conductor */
        get: operations["obtenerConductor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogo/tipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar los Tipos de documento del tenant */
        get: operations["listarTiposDocumento"];
        put?: never;
        /**
         * Agregar un Tipo de documento al catálogo
         * @description spec-005 R2/R10. El catálogo es configurable por tenant sin redeploy:
         *     cambios normativos se resuelven agregando o desactivando Tipos.
         */
        post: operations["agregarTipoDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogo/tipos/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar un Tipo (activar/desactivar, requerido)
         * @description spec-005 R10. Desactivar un Tipo impide registrar nuevos Documentos de ese
         *     Tipo sin afectar los existentes. `requerido` alimenta la invariante I3
         *     (requerido ausente ⇒ Semáforo rojo).
         */
        patch: operations["actualizarTipoDocumento"];
        trace?: never;
    };
    "/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos (filtrable por sujeto) */
        get: operations["listarDocumentos"];
        put?: never;
        /**
         * Registrar un documento con vencimiento
         * @description spec-005. Asocia un Documento a un Vehículo o Conductor con su fecha de
         *     vencimiento. El binario del adjunto se sube por separado vía
         *     `POST /documentos/{id}/adjunto`. Emite `DocumentoRegistrado`.
         */
        post: operations["registrarDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documentoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        /** Obtener un documento (con histórico de versiones) */
        get: operations["obtenerDocumento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documentoId}/adjunto": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Subir/reemplazar el archivo adjunto del documento
         * @description spec-005. Almacenamiento aislado por tenant.
         */
        put: operations["subirAdjuntoDocumento"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documentoId}/renovaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar un documento conservando histórico
         * @description spec-007. Crea una nueva versión vigente y conserva la anterior en el histórico.
         *     Emite `DocumentoRenovado`; si el sujeto vuelve a estar al día, rehabilita
         *     asignaciones (política P5).
         */
        post: operations["renovarDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cumplimiento/vehiculos/{vehiculoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        /**
         * Estado de cumplimiento (Semáforo) de un vehículo
         * @description spec-006. Devuelve el Semáforo y el detalle por documento.
         */
        get: operations["cumplimientoVehiculo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cumplimiento/conductores/{conductorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conductorId: components["parameters"]["ConductorId"];
            };
            cookie?: never;
        };
        /** Estado de cumplimiento (Semáforo) de un conductor */
        get: operations["cumplimientoConductor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cumplimiento/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar alertas de vencimiento vigentes
         * @description spec-006. Documentos por vencer (30/15/3 días) y vencidos del tenant.
         *     Alimenta el tablero de alertas del portal.
         */
        get: operations["listarAlertas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar servicios (agenda) */
        get: operations["listarServicios"];
        put?: never;
        /**
         * Crear un servicio
         * @description spec-008. Origen, destino, ventana horaria y cliente.
         */
        post: operations["crearServicio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/{servicioId}/asignacion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Asignar vehículo + conductor a un servicio
         * @description spec-008 + spec-009 (**regla de oro**). Valida que no haya **choque de ventana
         *     horaria** (409 `conflicto_horario`) y que el vehículo y el conductor estén
         *     **al día documentalmente** (consulta ACL a Cumplimiento):
         *     - Semáforo **rojo** ⇒ se rechaza con `409 incumplimiento` (emite `AsignacionRechazada`).
         *     - Semáforo **amarillo** ⇒ se permite pero la respuesta incluye `advertencias`.
         *     En éxito emite `ServicioAsignado`.
         */
        put: operations["asignarServicio"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/{servicioId}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar el estado del servicio (iniciar/finalizar/cancelar)
         * @description spec-010. Transiciones válidas: `Planificado→Iniciado→Finalizado` o
         *     `Planificado→Cancelado` (invariante S2). El conductor puede ejecutarlo **offline**
         *     y sincronizarlo después; por eso acepta `Idempotency-Key` y marca de tiempo del
         *     cliente. Emite `ServicioIniciado` / `ServicioFinalizado`.
         */
        post: operations["cambiarEstadoServicio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/{servicioId}/novedades": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reportar una novedad del servicio (offline, append-only)
         * @description spec-014 (Draft). Incidente/retraso, opcionalmente con foto (subida aparte).
         *     Append-only e idempotente. Emite `NovedadReportada`.
         */
        post: operations["reportarNovedad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/combustible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar tanqueos */
        get: operations["listarTanqueos"];
        put?: never;
        /**
         * Registrar un tanqueo (offline, append-only, idempotente)
         * @description spec-011. El cliente genera un UUID y lo envía en `Idempotency-Key`; el servidor
         *     **deduplica** para que los reintentos de sync no creen registros duplicados.
         *     Incluye la lectura de odómetro (actualiza el vehículo). Emite `CombustibleRegistrado`.
         */
        post: operations["registrarTanqueo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar cambios del servidor desde un cursor
         * @description spec-010. Delta sync para la app del conductor: agenda, documentos (semáforo) y
         *     datos de vehículo modificados desde `cursor`. Devuelve un nuevo `cursor` opaco
         *     para la siguiente sincronización.
         */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subir un lote de cambios generados offline
         * @description spec-010/011. Envía la cola de cambios del dispositivo (tanqueos, novedades,
         *     cambios de estado de servicio). Cada cambio lleva su `clientId` (UUID) para
         *     **deduplicación idempotente**. La respuesta indica el resultado por cambio,
         *     incluyendo conflictos a resolver.
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error con forma RFC 7807. */
        Problem: {
            /** @description Identificador del tipo de error (p. ej. conflicto_horario, incumplimiento). */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Detalle de errores de validación por campo. */
            errors?: {
                campo?: string;
                mensaje?: string;
            }[];
        };
        Pagina: {
            page: number;
            pageSize: number;
            total: number;
        };
        /** @description Monto monetario en COP (entero, sin decimales). */
        Money: {
            /**
             * @default COP
             * @enum {string}
             */
            moneda: "COP";
            /** @description Monto en pesos colombianos. */
            valor: number;
        };
        /**
         * @description Estado de cumplimiento. Verde/Amarillo/Rojo.
         * @enum {string}
         */
        Semaforo: "Vigente" | "PorVencer" | "Vencido";
        /** @description Referencia polimórfica a un Vehículo o Conductor. */
        SujetoRef: {
            /** @enum {string} */
            tipo: "vehiculo" | "conductor";
            /** Format: uuid */
            id: string;
        };
        RegistrarTenantRequest: {
            empresa: {
                razonSocial: string;
                nit: string;
            };
            administrador: {
                nombre: string;
                /** Format: email */
                correo: string;
            };
            /** @description Consentimiento Habeas Data (Ley 1581/2012). Debe ser true. */
            aceptaTratamientoDatos: boolean;
        };
        TenantCreado: {
            tenant?: components["schemas"]["Tenant"];
            administrador?: components["schemas"]["Usuario"];
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            razonSocial: string;
            nit: string;
            /** @enum {string} */
            plan: "Free" | "Starter" | "Pro" | "Enterprise";
            /** Format: date-time */
            creadoEn?: string;
        };
        /** @enum {string} */
        RolUsuario: "Administrador" | "Operador" | "GestorPlanilla" | "RepresentanteLegal" | "DuenoVehiculo" | "Conductor";
        InvitarUsuarioRequest: {
            nombre: string;
            /** Format: email */
            correo: string;
            roles: components["schemas"]["RolUsuario"][];
        };
        ActualizarUsuarioRequest: {
            roles?: components["schemas"]["RolUsuario"][];
            /** @enum {string} */
            estado?: "activo" | "suspendido";
        };
        Usuario: {
            /** Format: uuid */
            id: string;
            nombre: string;
            /** Format: email */
            correo: string;
            roles: components["schemas"]["RolUsuario"][];
            /** @enum {string} */
            estado: "invitado" | "activo" | "suspendido";
        };
        /** @enum {string} */
        ClaseVehiculo: "automovil" | "camioneta" | "van" | "microbus" | "bus" | "campero" | "otro";
        RegistrarVehiculoRequest: {
            /** @description Placa colombiana, p. ej. ABC123. Única por tenant. */
            placa: string;
            clase: components["schemas"]["ClaseVehiculo"];
            marca?: string;
            modelo?: string;
            anio?: number;
            /**
             * Format: uuid
             * @description Opcional. Referencia al propietario.
             */
            propietarioId?: string;
            odometroInicial?: number;
        };
        ActualizarVehiculoRequest: {
            marca?: string;
            modelo?: string;
            anio?: number;
            /** Format: uuid */
            propietarioId?: string;
            /** @enum {string} */
            estado?: "activo" | "inactivo";
        };
        Vehiculo: {
            /** Format: uuid */
            id: string;
            placa: string;
            clase: components["schemas"]["ClaseVehiculo"];
            marca?: string;
            modelo?: string;
            anio?: number;
            /** @description Última lectura conocida. */
            odometro?: number;
            semaforo?: components["schemas"]["Semaforo"];
            /** @enum {string} */
            estado: "activo" | "inactivo";
        };
        RegistrarOdometroRequest: {
            lectura: number;
            /** @enum {string} */
            fuente: "manual" | "tanqueo" | "servicio";
            /** Format: date-time */
            registradoEn?: string;
        };
        LecturaOdometro: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehiculoId: string;
            lectura: number;
            fuente?: string;
            /** Format: date-time */
            registradoEn?: string;
        };
        RegistrarConductorRequest: {
            nombre: string;
            documentoIdentidad: string;
            /**
             * Format: uuid
             * @description Opcional: vínculo con el Usuario que usa la app.
             */
            usuarioId?: string;
            licencia: {
                numero: string;
                /** @description Categoría de licencia, p. ej. C1. */
                categoria: string;
                /** Format: date */
                vencimiento: string;
            };
        };
        Conductor: {
            /** Format: uuid */
            id: string;
            nombre: string;
            /** Format: uuid */
            usuarioId?: string;
            licencia?: {
                numero?: string;
                categoria?: string;
                /** Format: date */
                vencimiento?: string;
            };
            semaforo?: components["schemas"]["Semaforo"];
        };
        TipoDocumentoCatalogo: {
            /** @description P. ej. SOAT, RTM, LICENCIA. */
            codigo: string;
            /** @enum {string} */
            aplicaA: "vehiculo" | "conductor";
            /** @description Alimenta la invariante I3 (ausente ⇒ rojo). */
            requerido: boolean;
            activo: boolean;
        };
        AgregarTipoDocumentoRequest: {
            codigo: string;
            /** @enum {string} */
            aplicaA: "vehiculo" | "conductor";
            /** @default false */
            requerido: boolean;
        };
        /** @description Campos opcionales; solo se actualiza lo enviado. */
        ActualizarTipoDocumentoRequest: {
            activo?: boolean;
            requerido?: boolean;
        };
        RegistrarDocumentoRequest: {
            sujeto: components["schemas"]["SujetoRef"];
            /** @description Código del Tipo de documento (catálogo configurable): SOAT, RTM, TARJETA_OPERACION, LICENCIA, EXAMEN_MEDICO, POLIZA_CONTRACTUAL, POLIZA_EXTRACONTRACTUAL, etc. */
            tipo: string;
            numero?: string;
            /** Format: date */
            expedicion?: string;
            /** Format: date */
            vencimiento: string;
        };
        RenovarDocumentoRequest: {
            numero?: string;
            /** Format: date */
            expedicion?: string;
            /** Format: date */
            vencimiento: string;
        };
        Documento: {
            /** Format: uuid */
            id: string;
            sujeto: components["schemas"]["SujetoRef"];
            tipo: string;
            numero?: string;
            /** Format: date */
            expedicion?: string;
            /** Format: date */
            vencimiento: string;
            estado: components["schemas"]["Semaforo"];
            tieneAdjunto?: boolean;
            /** @description Número de versión (renovaciones). */
            version?: number;
            /** @description Versiones anteriores (renovaciones). */
            historico?: {
                version?: number;
                /** Format: date */
                vencimiento?: string;
                /** Format: date-time */
                reemplazadoEn?: string;
            }[];
        };
        EstadoCumplimiento: {
            sujeto: components["schemas"]["SujetoRef"];
            semaforo: components["schemas"]["Semaforo"];
            documentos?: {
                /** Format: uuid */
                documentoId?: string;
                tipo?: string;
                /** Format: date */
                vencimiento?: string;
                estado?: components["schemas"]["Semaforo"];
                diasRestantes?: number;
            }[];
        };
        Alerta: {
            /** Format: uuid */
            documentoId: string;
            sujeto: components["schemas"]["SujetoRef"];
            tipo?: string;
            /** @enum {string} */
            estado: "por_vencer" | "vencido";
            /** Format: date */
            vencimiento: string;
            /** @description Negativo si ya venció. */
            diasRestantes?: number;
        };
        /** @enum {string} */
        EstadoServicio: "Planificado" | "Iniciado" | "Finalizado" | "Cancelado";
        VentanaHoraria: {
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fin: string;
        };
        CrearServicioRequest: {
            origen: string;
            destino: string;
            ventana: components["schemas"]["VentanaHoraria"];
            cliente?: string;
        };
        AsignarServicioRequest: {
            /** Format: uuid */
            vehiculoId: string;
            /** Format: uuid */
            conductorId: string;
        };
        CambiarEstadoServicioRequest: {
            /** @enum {string} */
            accion: "iniciar" | "finalizar" | "cancelar";
            /**
             * Format: date-time
             * @description Marca de tiempo del cliente (puede ser offline).
             */
            ocurridoEn?: string;
            /** @description Lectura al iniciar/finalizar, si aplica. */
            odometro?: number;
            /**
             * Format: uuid
             * @description UUID del cambio para idempotencia.
             */
            clientId?: string;
        };
        Asignacion: {
            /** Format: uuid */
            servicioId: string;
            /** Format: uuid */
            vehiculoId: string;
            /** Format: uuid */
            conductorId: string;
            /** @description Advertencias no bloqueantes (p. ej. semáforo amarillo — spec-009). */
            advertencias?: string[];
        };
        Servicio: {
            /** Format: uuid */
            id: string;
            origen: string;
            destino: string;
            ventana: components["schemas"]["VentanaHoraria"];
            cliente?: string;
            estado: components["schemas"]["EstadoServicio"];
            asignacion?: components["schemas"]["Asignacion"];
            /** Format: date-time */
            inicioReal?: string;
            /** Format: date-time */
            finReal?: string;
        };
        ReportarNovedadRequest: {
            /** @enum {string} */
            tipo: "incidente" | "retraso" | "siniestro" | "otro";
            descripcion?: string;
            /** Format: date-time */
            ocurridoEn: string;
            /** Format: uuid */
            clientId: string;
            tieneFoto?: boolean;
        };
        Novedad: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            servicioId: string;
            tipo: string;
            descripcion?: string;
            /** Format: date-time */
            ocurridoEn: string;
            tieneFoto?: boolean;
        };
        RegistrarTanqueoRequest: {
            /** Format: uuid */
            vehiculoId: string;
            /** @description Litros o galones según configuración del tenant. */
            litros: number;
            valor: components["schemas"]["Money"];
            odometro: number;
            /** Format: date-time */
            tanqueadoEn?: string;
            /**
             * Format: uuid
             * @description UUID del cambio para idempotencia (append-only).
             */
            clientId: string;
        };
        Tanqueo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehiculoId: string;
            litros: number;
            valor: components["schemas"]["Money"];
            odometro: number;
            /** Format: date-time */
            tanqueadoEn?: string;
        };
        SyncPullResponse: {
            /** @description Cursor para la próxima sincronización. */
            cursor: string;
            servicios?: components["schemas"]["Servicio"][];
            documentos?: components["schemas"]["Documento"][];
            vehiculos?: components["schemas"]["Vehiculo"][];
        };
        /** @description Un cambio generado offline en el dispositivo. */
        SyncCambio: {
            /**
             * Format: uuid
             * @description UUID idempotente del cambio.
             */
            clientId: string;
            /** @enum {string} */
            entidad: "tanqueo" | "novedad" | "estado_servicio";
            /** @enum {string} */
            operacion: "crear" | "actualizar";
            /** @description Cuerpo del cambio (forma según la entidad). */
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            ocurridoEn?: string;
        };
        SyncPushRequest: {
            cambios: components["schemas"]["SyncCambio"][];
        };
        SyncPushResultado: {
            /** Format: uuid */
            clientId: string;
            /** @enum {string} */
            resultado: "confirmado" | "duplicado" | "conflicto" | "error";
            /**
             * Format: uuid
             * @description Id asignado por el servidor (si se creó).
             */
            serverId?: string;
            version?: number;
            problema?: components["schemas"]["Problem"];
        };
        SyncPushResponse: {
            resultados: components["schemas"]["SyncPushResultado"][];
        };
    };
    responses: {
        /** @description Falta o es inválido el token de autenticación. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El rol del usuario no permite esta operación (RBAC). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso no encontrado en el tenant actual. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Error de validación de la solicitud. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
        /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
        IdempotencyKey: string;
        UsuarioId: string;
        VehiculoId: string;
        ConductorId: string;
        DocumentoId: string;
        ServicioId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registrarTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant y administrador creados. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCreado"];
                };
            };
            /** @description Ya existe un tenant/administrador con ese identificador o correo. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    obtenerTenantActual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant actual (derivado del JWT). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listarUsuarios: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de usuarios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Usuario"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    invitarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitarUsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario invitado (estado `invitado`). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description El correo ya pertenece a un usuario del tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    actualizarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuarioId: components["parameters"]["UsuarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarUsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listarVehiculos: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de vehículos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Vehiculo"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registrarVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarVehiculoRequest"];
            };
        };
        responses: {
            /** @description Vehículo creado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehiculo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Ya existe un vehículo con esa placa en el tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    obtenerVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehículo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehiculo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    actualizarVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarVehiculoRequest"];
            };
        };
        responses: {
            /** @description Vehículo actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehiculo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    registrarOdometro: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarOdometroRequest"];
            };
        };
        responses: {
            /** @description Lectura registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturaOdometro"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description La lectura es menor que la última registrada (viola monotonía). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listarConductores: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de conductores. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Conductor"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registrarConductor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarConductorRequest"];
            };
        };
        responses: {
            /** @description Conductor creado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conductor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    obtenerConductor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conductorId: components["parameters"]["ConductorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conductor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conductor"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listarTiposDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tipos del catálogo (activos e inactivos). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumentoCatalogo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    agregarTipoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarTipoDocumentoRequest"];
            };
        };
        responses: {
            /** @description Tipo agregado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumentoCatalogo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Ya existe un Tipo con ese código en el tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    actualizarTipoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarTipoDocumentoRequest"];
            };
        };
        responses: {
            /** @description Tipo actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDocumentoCatalogo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listarDocumentos: {
        parameters: {
            query?: {
                sujetoTipo?: "vehiculo" | "conductor";
                sujetoId?: string;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de documentos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Documento"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registrarDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarDocumentoRequest"];
            };
        };
        responses: {
            /** @description Documento creado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Documento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    obtenerDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Documento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    subirAdjuntoDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Adjunto almacenado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Archivo demasiado grande. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    renovarDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentoId: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenovarDocumentoRequest"];
            };
        };
        responses: {
            /** @description Documento renovado (nueva versión vigente). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Documento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    cumplimientoVehiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculoId: components["parameters"]["VehiculoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de cumplimiento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoCumplimiento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cumplimientoConductor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conductorId: components["parameters"]["ConductorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de cumplimiento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoCumplimiento"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listarAlertas: {
        parameters: {
            query?: {
                estado?: "por_vencer" | "vencido";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de alertas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Alerta"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listarServicios: {
        parameters: {
            query?: {
                desde?: string;
                hasta?: string;
                estado?: components["schemas"]["EstadoServicio"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de servicios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Servicio"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    crearServicio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearServicioRequest"];
            };
        };
        responses: {
            /** @description Servicio creado (estado Planificado). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    asignarServicio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsignarServicioRequest"];
            };
        };
        responses: {
            /** @description Asignación creada (puede incluir advertencias por semáforo amarillo). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asignacion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Conflicto. `type` indica el motivo: `conflicto_horario` (solapamiento) o
             *     `incumplimiento` (semáforo rojo, regla de oro — spec-009).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cambiarEstadoServicio: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarEstadoServicioRequest"];
            };
        };
        responses: {
            /** @description Estado actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Transición de estado inválida (viola invariante S2). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reportarNovedad: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                servicioId: components["parameters"]["ServicioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportarNovedadRequest"];
            };
        };
        responses: {
            /** @description Novedad registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Novedad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listarTanqueos: {
        parameters: {
            query?: {
                vehiculoId?: string;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de tanqueos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina"] & {
                        items?: components["schemas"]["Tanqueo"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registrarTanqueo: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarTanqueoRequest"];
            };
        };
        responses: {
            /**
             * @description Reintento idempotente: ya existía un tanqueo con ese `Idempotency-Key`.
             *     Se devuelve el registro existente sin crear uno nuevo.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tanqueo"];
                };
            };
            /** @description Tanqueo registrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tanqueo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    syncPull: {
        parameters: {
            query?: {
                /** @description Cursor opaco de la última sincronización. Ausente = bootstrap inicial. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lote de cambios + cursor siguiente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos (offline). */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Resultado por cada cambio del lote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
}
